# Generated by Django 5.2.3 on 2025-06-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='payment_method',
            field=models.CharField(choices=[('debito', 'Debito'), ('credito', 'Credito'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro')], max_length=10),
        ),
    ]
