# Generated by Django 5.2.3 on 2025-06-23 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_cashoutflow_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='installments',
            field=models.IntegerField(default=1, verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='payment_method',
            field=models.CharField(choices=[('debito', 'Debito'), ('credito', 'Credito'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro')], max_length=10, verbose_name='Método de pagamento'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='payment_type',
            field=models.CharField(choices=[('single', 'À Vista'), ('installment', 'Parcelado')], default='single', max_length=15, verbose_name='Tipo de pagamento'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
